# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_U_arma <- function(U, V, ddiff, ddratio, alpha, sigma) {
    .Call('_scINSIGHT2_update_U_arma', PACKAGE = 'scINSIGHT2', U, V, ddiff, ddratio, alpha, sigma)
}

update_par_arma <- function(U, V, ddiff, ddratio, alpha) {
    .Call('_scINSIGHT2_update_par_arma', PACKAGE = 'scINSIGHT2', U, V, ddiff, ddratio, alpha)
}

matrix_deviance <- function(pred, obs) {
    .Call('_scINSIGHT2_matrix_deviance', PACKAGE = 'scINSIGHT2', pred, obs)
}

iteration <- function(U, V, Y, beta, X, alpha, sigma, latentpart, regpart, logs, maxIter, d, n, m, llast, tol1, tol2, p) {
    .Call('_scINSIGHT2_iteration', PACKAGE = 'scINSIGHT2', U, V, Y, beta, X, alpha, sigma, latentpart, regpart, logs, maxIter, d, n, m, llast, tol1, tol2, p)
}

multMat <- function(m1, m2) {
    .Call('_scINSIGHT2_multMat', PACKAGE = 'scINSIGHT2', m1, m2)
}

